name:                convexPartitioning
version:             0.1.0.0
github:              "mdiamantino/convexPartitioning"
license:             BSD3
author:              "Mark Diamantino Caribé"
maintainer:          "mark.diamantinocaribe@student.kuleuven.be"
copyright:           "2021 Mark Diamantino Caribé"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mdiamantino/convexPartitioning#readme>

dependencies:
- base >= 4.7 && < 5
- hgeometry >= 0.12.0.1
- hgeometry-combinatorial >= 0.12.0.1
library:
  source-dirs: src

executables:
  convexPartitioning-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - convexPartitioning

tests:
  convexPartitioning-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - convexPartitioning
